// This file was autogenerated by bin/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/js/app.js', ['tt.app'], ['tt.app.start']);
goog.addDependency('../../../../src/js/app/start.js', ['tt.app.start'], ['tt.tpl.base']);
goog.addDependency('../../../../src/js/model/base/Model.js', ['tt.model.base.Model'], ['goog.events.Event', 'tt.model.base.ModelEvent']);
goog.addDependency('../../../../src/js/model/base/ModelEvent.js', ['tt.model.base.ModelEvent'], ['goog.events.Event']);
goog.addDependency('../../../../src/js/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJs', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri', 'soydata.VERY_UNSAFE'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.soy.data.SanitizedContentKind', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../../src/js/utils/localStorage.js', ['tt.utils.localStorage'], []);
goog.addDependency('../../../../src/templates/base.soy.js', ['tt.tpl.base'], ['soy', 'soydata']);
